### ISSUE TITLE
trouble with grid cell background color

### ISSUE THREAD

**Issue by adamosoftware** [adamosoftware/css-grid-sample#1]
After adding search box to my grid layout, the height of the text box is causing some margin to appear in the rest of the toolbar and "home" cells. The blue background is supposed to fill all of the `.toolarea` content, but there's white background color showing through.

![image](https://user-images.githubusercontent.com/4549398/79053928-11033d00-7c0f-11ea-97d3-4b1d2caf4058.png)

Impacted markup is [index.html](https://github.com/adamosoftware/css-grid-sample/blob/master/index.html) and the css is [styles.less](https://github.com/adamosoftware/css-grid-sample/blob/master/styles.less)

**Comment by Amsteri21** [comment]
You need to add height 100% to .toolarea and .home-cell

**Comment by Amsteri21** [comment]
http://joxi.ru/52axKOzTbnGGgm

**Comment by kgoyal000** [comment]
hey i check on upwork but i am out of connects i found its solution its because of position relative
.ui.input{
margin-bottom:-21px
}
use this i will correct this
if you want to chat with me 
https://www.upwork.com/freelancers/~01193040d9ff44fd6e

**Comment by Amsteri21** [comment]
my upwork: https://www.upwork.com/freelancers/~010dc3f3e5aacaf80b

**Comment by Amsteri21** [comment]
I added a proposal to your project.

**Comment by Amsteri21** [comment]
I can not send a message to you on Upwork.

**Comment by sangram203** [comment]
This is due to flexbox model

**Comment by Amsteri21** [comment]
.ui.input{
margin-bottom:-21px
}

it is bad practice.

**Comment by Amsteri21** [comment]
`.toolarea {
  height: 100%;
  background-color: #01294a;
  color: white;
}
#app-grid > #home-cell {
  height: 100%;
  grid-area: home;
  text-align: center;
  align-self: center;
  background-color: #01294a;
  color: white;
}`

**Comment by Aghawaqasahmad** [comment]
I see your message on upwork. Here is a solution first add the Id in your nav (id="nav-col") and  just add padding on these both elements
#home-cell, #nav-cell { padding: 1.3rem; }

**Comment by adamosoftware** [comment]
thank you @Aghawaqasahmad @Amsteri21 @kgoyal000 @sangram203 for weighing in. Fix ended up being removal of `align-self` attribute 62f5ff4e708f86bc633fe8f082fdf4ebb558eefb

**Comment by Aghawaqasahmad** [comment]
Wow. Good to hear.
